[secrets]
AAA = [
  "ssh/AAA/id_ed25519",
  "ssh/AAA/id_ed25519.pub",
  "wg/AAA/wg0.private",
  "wg/AAA/wg0.public",
]
BBB = [
  "ssh/BBB/id_ed25519",
  "ssh/BBB/id_ed25519.pub",
  "wg/BBB/wg0.private",
  "wg/BBB/wg0.public",
]

[additional_imports]
AAA = [
  "ssh/BBB/id_ed25519.pub",
  "wg/BBB/wg0.public",
]
BBB = [ "wg/AAA/wg0.public" ]
