# Export rule that applies to every machine, substituting <$profile>
# with the machine name
[[exports.shared]]
source="/home/USERNAME/.ssh"
endpoint="ssh/$profile"
files = ["id_ed25519", "id_ed25519.pub"]

# Export rule that applies only to machine1
[[exports.machine1]]
source="/secrets/something"
endpoint="machine1/something"
files = ["secret1", "secret2"]

# You can have multiple rules for the same machine, in order to export
# multiple secrets
[[exports.machine1]]
source="/secrets/something-else"
endpoint="machine1/something-else"
files = ["secret1", "secret2"]

# Imports rule that applies to every machine
[[imports.shared]]
source="ssh/$profile"
endpoint="/home/USERNAME/.ssh"
files = ["id_ed25519", "id_ed25519.pub"]
# This symlinks the user ssh keys to the root's ssh keys, in order to
# be able to use them even when running sudo
symlinks_to="/root/.ssh"

# Inverse of the first export rule specific to machine1
[[imports.machine1]]
source="machine1/something"
endpoint="/secrets/something"
files = ["secret1", "secret2"]

# Inverse of the first export rule specific to machine2
[[imports.machine1]]
source="machine1/something-else"
endpoint="/secrets/something-else"
files = ["secret1", "secret2"]

# Rule to import machine1's ssh public key to machine2 to use them in
# configurations and authorized_keys
[[imports.machine2]]
source="ssh/machine1"
endpoint="/secrets/ssh-pub-keys/machine1"
files = ["id_ed25519.pub"]
